#
# Spec file generated by kdist version v0.0.4-56-gf790
#
Name:          kernel-headers
Summary:       Linux kernel header files mostly used by your C library
Version:       3.6.7
Release:       1
License:       GPL v2
Group:         System/Kernel and hardware
URL:           http://www.kernel.org
Source0:       kernel-headers-3.6.7-1.tar.bz2
AutoReqProv:   no
BuildRequires: rsync
Epoch:         1
BuildArch:     noarch

%rename linux-userspace-headers

%define debug_package %{nil}
%define __check_files %{nil}

%description
C header files from the Linux kernel. The header files define
structures and constants that are needed for building most
standard programs, notably the C library.

This package is not suitable for building kernel modules, you
should use the 'kernel-devel' package instead.

%prep
%setup -q -n kernel-headers-3.6.7-1

%install
make INSTALL_HDR_PATH=%{buildroot}/usr headers_install

%files
/usr/include/*



%changelog
*Fri Aug 17 2012 Alex Burmashev <alex.burmashev@rosalab.ru> 3.5.1-1
- Release 3.5.1-1

