#
# Spec file generated by kdist version v0.4-12-g6143
#
%define name		kernel-headers
%define version		3.3.0
%define src_uname_r	3.3.0-2
%define source_release	2
%define build_release	1%{nil}
%define archive		kernel-headers-3.3.0-2.1

%define build_srpm	1
%define no_source	1

%define _source_path	/usr/src/linux-%{src_uname_r}
%if %no_source
%define source_path	%{_source_path}/
%else
%define source_path	./
%endif

Name:			%{name}
Summary:		Linux kernel header files mostly used by your C library
Version:		%{version}
Release:		%mkrel %{source_release}.%{build_release}
Epoch:			1
License:		GPLv2
Group:			System/Kernel and hardware
URL:			http://www.kernel.org
%if %build_srpm
Source:			%{archive}.tar.bz2
%endif
BuildRoot:		%{_tmppath}/%{name}-%{version}-root
AutoReqProv:		no
%if %no_source
BuildRequires:		kernel-source = %{version}-%{mkrel %{source_release}}
%endif

%rename linux-userspace-headers

%define debug_package	%{nil}
%define __check_files	%{nil}

%description
C header files from the Linux kernel. The header files define
structures and constants that are needed for building most
standard programs, notably the C library.

This package is not suitable for building kernel modules, you
should use the '%{name}-devel' package instead.

%if %build_srpm
%prep
%setup -q -n %{archive}
%endif

%install
# Unfortunately we can't use "make outputmakefile" here because for
# some reasons this target requires a .config installed.
%if %no_source
extra_opts="O=$(pwd)"
%endif
make -C %{source_path} INSTALL_HDR_PATH=%{buildroot}/usr $extra_opts headers_install

%clean
rm -rf %{buildroot}

%files
%defattr (-, root, root)
/usr/include


%changelog
* Thu Mar 22 2012 Franck Bui <franck.bui@mandriva.com> 
  + Mandriva Release v3.3-2
  + drm/i915: enable RC6 by default on Sandy Bridge
